---
# List of plays
-
  # Hosts: where our play will run and options it will run with
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: always

  # Vars: variables that will apply to the play, on all targets 

  # Tasks: the list of tasks that will be executed within 
  #        the play, this section can also be used for 
  #        pre and post tasks
  tasks:
    # from https://superuser.com/questions/1395954/ansible-playbook-to-determine-os-release
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
    # Detect if we are running on a WSL2 environment
  - name: Set wsl2_environment fact default to false
    set_fact:
      wsl2_environment: false
  - name: Set wsl2_environment fact True
    set_fact:
      wsl2_environment: true
    when: ansible_kernel is search("microsoft-standard-WSL2")  
  # fix for .gnupg/ permissions when building custom images
  - name: Add fix for .gnupg/ permissions
    lineinfile:
      path: "/etc/bash.bashrc"
      line: "chmod 700 ~/.gnupg/"    
  - name: Add custom prompt to /etc/skel/.profile
    lineinfile:
      path: "/etc/skel/.profile"
      line: 'export PS1="\e[0;32m[\w]\$ \e[0m"'

  # Handlers: the list of handlers that are executed as a notify 
  #           key from a task

  # Roles: list of roles to be imported into the play
  roles:
  - role: irixjp.role_example_hello

# Add additional plays here (remember the list entry -)
# Be sure to use the same hosts and connection entries above
# addtional plays

-
  # install OpenJDK 11
  hosts: localhost
  connection: local
  tasks:
  - name: Download OpenJDK 11 tarball
    shell: wget https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz -O /home/kasm-default-profile/openjdk-11+28_linux-x64_bin.tar.gz
  - name: Extract OpenJDK 11 binaries
    unarchive:
      src: /home/kasm-default-profile/openjdk-11+28_linux-x64_bin.tar.gz
      dest: /opt
      remote_src: yes
      creates: /opt/jdk-11/release
  - name: Delete OpenJDK 11 tarball
    shell: rm /home/kasm-default-profile/openjdk-11+28_linux-x64_bin.tar.gz
  - name: Update alternatives so the command, java, points to installed jdk
    shell: update-alternatives --install /usr/bin/java java /opt/jdk-11/bin/java 100
  - name: Update alternatives so the command, javac, points to installed jdk
    shell: update-alternatives --install /usr/bin/javac javac /opt/jdk-11/bin/javac 100

-
  # install chrome
  hosts: localhost
  connection: local
  gather_facts: yes

  roles:
    - role: webarchitect609.google_chrome

-
  # install keychain, git, and @capsulecorplab .vimrc and .gitconfig
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: install_utilities

  vars:
    git_version: "2.36.1"
    git_version_to_install: "1:{{ git_version }}-0ppa1~ubuntu20.04.1"
    keychain_version: "2.8.5"
    keychain_version_to_install: "{{ keychain_version }}-1"
    keychain_version_expected: "{{ keychain_version }}.."

  tasks:
  - name: Install dh-autoreconf
    apt:
      name: dh-autoreconf
      update_cache: yes
  - name: Install libcurl4-gnutls-dev
    apt:
      name: libcurl4-gnutls-dev
      update_cache: yes
  - name: Install libexpat1-dev
    apt:
      name: libexpat1-dev
      update_cache: yes
  - name: Install gettext
    apt:
      name: gettext
      update_cache: yes
  - name: Install libz-dev
    apt:
      name: libz-dev
      update_cache: yes
  - name: Install libssl-dev
    apt:
      name: libssl-dev
      update_cache: yes
  - name: Install install-info
    apt:
      name: install-info
      update_cache: yes
  - name: Download git (v2.36.1) tarball
    shell: wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.36.1.tar.gz -O /home/kasm-default-profile/git-2.36.1.tar.gz
  - name: Extract git source files
    unarchive:
      src: /home/kasm-default-profile/git-2.36.1.tar.gz
      dest: /home/kasm-default-profile/
      remote_src: yes
      creates: /home/kasm-default-profile/git-2.36.1/README.md
  - name: Delete git tarball
    shell: rm /home/kasm-default-profile/git-2.36.1.tar.gz
  - name: Build git
    shell:
      cmd: make configure && ./configure --prefix=/usr && make > /tmp/git_build_output.txt 2>&1 && make install
      chdir: /home/kasm-default-profile/git-2.36.1
      executable: /bin/bash
  - name: Delete git source files
    shell: rm -rf /home/kasm-default-profile/git-2.36.1
  - name: Install Keychain
    apt:
      name: "keychain={{ keychain_version_to_install }}"
      update_cache: yes
  - name: Get git version
    shell: git version | sed 's/[[:alpha:]|(|[:space:]]//g'
    register: installed_git_version
  - name: Get keychain version
    shell: 
      cmd: keychain -V 2> >(grep -i keychain) 2> >(sed 's/[[:alpha:]|(|[:space:]]//g') | fgrep '*' | sed 's/[*~://]//g'
      executable: /bin/bash
    register: installed_keychain_version
  - name: Display git and keychain versions
    debug:
      msg: "git = {{ installed_git_version.stdout }} | keychain = {{ installed_keychain_version.stdout }}"
  - name: Test git version
    fail:
      msg: "Git Version Error: Expected {{ git_version }} | Found {{ installed_git_version.stdout }}"
    when: installed_git_version.stdout != git_version  
  - name: Test keychain version
    fail:
      msg: "Keychain Version Error: Expected {{ keychain_version_expected }} | Found {{ installed_keychain_version.stdout }}"
    when: installed_keychain_version.stdout != keychain_version_expected
  - name: Install @capsulecorplab .vimrc
    get_url:
      url: https://gist.githubusercontent.com/capsulecorplab/495058e7a57ed8adaed3c40c80d09739/raw/4a6e6f6ff92b96919be111c9cbb5a4a21ab472d2/.vimrc
      dest: /home/kasm-default-profile/
  - name: Install @capsulecorplab .gitconfig
    get_url:
      url: https://gist.githubusercontent.com/capsulecorplab/401ba2fe0857a328f2a626adbf078cc6/raw/b89a6234f0d620ff60bcfe37f95de197b8772377/.gitconfig
      dest: /home/kasm-default-profile/

-
  # install Cross-compile toolchain for AVR & ARM targets
  hosts: localhost
  connection: local
  tasks:
  - name: Install gcc-avr with Apt
    apt:
      name: gcc-avr
      update_cache: yes
  - name: Install binutils-avr with Apt
    apt:
      name: binutils-avr
      update_cache: yes
  - name: Install gdb-avr with Apt
    apt:
      name: gdb-avr
      update_cache: yes
  - name: Install avr-libc with Apt
    apt:
      name: avr-libc
      update_cache: yes
  - name: Install avrdude with Apt
    apt:
      name: avrdude
      update_cache: yes
  - name: Install gcc-arm-linux-gnueabihf with Apt
    apt:
      name: gcc-arm-linux-gnueabihf
      update_cache: yes
  - name: Install g++-arm-linux-gnueabihf with Apt
    apt:
      name: g++-arm-linux-gnueabihf
      update_cache: yes
  - name: Install gdb-multiarch with Apt
    apt:
      name: gdb-multiarch
      update_cache: yes
  - name: Install build-essential with Apt
    apt:
      name: build-essential
      update_cache: yes
  - name: Install libssl-dev
    apt:
      name: libssl-dev
      update_cache: yes
  - name: Download cmake tarball
    shell: wget http://www.cmake.org/files/v3.23/cmake-3.23.1.tar.gz -O /home/kasm-default-profile/cmake-3.23.1.tar.gz
  - name: Extract cmake source files
    unarchive:
      src: /home/kasm-default-profile/cmake-3.23.1.tar.gz
      dest: /home/kasm-default-profile/
      remote_src: yes
      creates: /home/kasm-default-profile/cmake-3.23.1/README
  - name: Delete cmake tarball
    shell: rm /home/kasm-default-profile/cmake-3.23.1.tar.gz
  - name: Build cmake
    shell:
      cmd: ./configure && make > /tmp/cmake_build_output.txt 2>&1 && make install
      chdir: /home/kasm-default-profile/cmake-3.23.1/
      executable: /bin/bash
  - name: Delete cmake source files
    shell: rm -rf /home/kasm-default-profile/cmake-3.23.1/
  - name: Download Arm toolchain tarball
    shell: wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 -O /home/kasm-default-profile/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
  - name: Extract Arm toolchain source files
    unarchive:
      src: /home/kasm-default-profile/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
      dest: /opt
      remote_src: yes
  - name: Delete Arm toolchain tarball
    shell: rm /home/kasm-default-profile/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
  - name: Create symbolic links for Arm toolchain binaries
    shell: ln -s /opt/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-* /usr/bin/
  - name: Download Arduino v1.8.13 tarball
    shell: wget https://downloads.arduino.cc/arduino-1.8.13-linux64.tar.xz -O /home/kasm-default-profile/arduino-1.8.13-linux64.tar.xz
  - name: Extract Arduino source files
    unarchive:
      src: /home/kasm-default-profile/arduino-1.8.13-linux64.tar.xz
      dest: /opt
      remote_src: yes
  - name: Delete Arduino tarball
    shell: rm -rf /home/kasm-default-profile/arduino-1.8.13-linux64.tar.xz
  - name: Install Arduino
    shell:
      cmd: ./install.sh
      chdir: /opt/arduino-1.8.13
      executable: /bin/bash
  - name: Create bin directory needed for Teensyduino cmake build system in Arduino source directory
    shell: mkdir -p /opt/arduino-1.8.13/hardware/tools/arm/bin
  - name: Create symbolic links needed for Teensyduino cmake build system in Arduino source directory
    shell: ln -s /opt/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-* /opt/arduino-1.8.13/hardware/tools/arm/bin

-
  # install Python packages with pip
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
  - name: Update OS to point python to python3
    apt:
      name: python-is-python3
      update_cache: yes
  - name: Install pip for python3 with Apt
    apt:
      name: python3-pip
      update_cache: yes
  - name: Install python packages used as dependencies with pip
    pip:
      name:
        - pint
        - MarkupSafe<2.0.0
        - jinja2==2.11.3
        - Werkzeug==2.0.1
        - setuptools_scm
        - urllib3
  - name: Install python packages with pip
    pip:
      name:
        - jupyterlab
        - notebook
        - voila
        - urllib3
        - fprime-tools==3.0.1
        - fprime-fpp==1.0.1
        - fprime-gds==3.0.2

- 
  # install sudo for the vs-code role below 
  hosts: localhost
  connection: local
  tasks:
  - name: Install Sudo
    apt:
      name: sudo
      update_cache: yes
  - name: Preserve DONT_PROMPT_WSL_INSTALL in sudoers
    lineinfile:
      path: "/etc/sudoers"
      line: "Defaults        env_keep += \"DONT_PROMPT_WSL_INSTALL\""
    when: wsl2_environment

-
# add dev user to give vs code somewhere to install extensions
  hosts: localhost
  connection: local
  tasks:
  - name: Add dev user
    user:
      name: dev
      uid: 1001

-
  # install the remainder of the tools
  hosts: localhost
  connection: local
  environment: 
    DONT_PROMPT_WSL_INSTALL: 1
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: "dev"
          visual_studio_code_extensions:
            - ms-python.python
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings: {
            "extensions.ignoreRecommendations": true,
            "update.mode": "none",
            "extensions.autoUpdate": false,
            "extensions.autoCheckUpdates": false,
            "terminal.integrated.profiles.linux": {
              "bash (login)": {
                "path": "bash",
                "args": ["-l"]
                }
              },
            "terminal.integrated.defaultProfile.linux": "bash (login)" 
          }  

-
  # Copy VS Code changes to kasm-default-profile and lean up (remove) dev user now that vs code is installed
  hosts: localhost
  connection: local
  tasks:
  - name: Copy VS Code changes to kasm-default-profile
    shell: 
      cmd: cp -r /home/dev/.config/Code/ /home/kasm-default-profile/.config/Code/ && cp -r /home/dev/.vscode/ /home/kasm-default-profile/.vscode/
  - name: Remove dev user
    user:
      name: dev
      state: absent
      remove: yes 

# Three dots indicate the end of a YAML document
...
